backend:
  name: git-gateway
  
publish_mode: editorial_workflow  
media_folder: static/img
public_folder: /img

collections:
  - name: "VJLP3-NoForm"
    label: "VJ Landing Page 3"
    format: 'frontmatter'
    folder: "assets/content/landing-page"
    create: true
    identifier_field: "promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    show_preview_links: true
    editor:
      preview: true
    fields:
      - {label: "Promo Title", name: "promo_title", widget: "string"}
      - {label: "Promo Description", name: "promo_description", widget: "string"}
      - {label: "Promo Join Button", name: "promo_join_button", widget: "string"}
      - {label: "Header Login Button", name: "header_login_button", widget: "string"}
      - {label: "Header Join Button", name: "header_join_button", widget: "string"}
      - {label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'vjlp1'
    label: 'VJLP1'
    format: 'json'
    folder: 'assets/content/vjlp1'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    show_preview_links: true
    editor:
      preview: true
    fields:
      - {label: "Promotion Title", name: "promotion-title", widget: "string"}
      - {label: "Promotion Subtitle", name: "promotion-subtitle", widget: "string"}
      - {label: "Promotion banner", name: promotion-banner, widget: image, required: false}
      - {label: "Promotion Button", name: promotion-button, widget: image, required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}