backend:
  name: git-gateway
  
publish_mode: editorial_workflow  
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: 'vjlp1'
    label: 'VJLP1'
    format: 'json'
    folder: 'assets/content/vjlp1'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    show_preview_links: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'vjlp3'
    label: 'VJLP3'
    format: 'json'
    folder: 'assets/content/vjlp3'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    show_preview_links: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}