backend:
  name: git-gateway
  
publish_mode: editorial_workflow  
media_folder: static/img
public_folder: /img

collections:
  - name: "VJLP3-NoForm"
    label: "VJ Landing Page 3"
    format: 'frontmatter'
    folder: "assets/content/landing-page"
    create: true
    identifier_field: "promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Promo Title", name: "promo_title", widget: "string"}
      - {label: "Promo Description", name: "promo_description", widget: "string"}
      - {label: "Promo Join Button", name: "promo_join_button", widget: "string"}
      - {label: "Header Login Button", name: "header_login_button", widget: "string"}
      - {label: "Header Join Button", name: "header_join_button", widget: "string"}
      - {label: 'Body', name: 'body', widget: 'markdown' }