backend:
  name: git-gateway
  #name: github
  #repo: kenkoy/nuxt-netlify-landing-page
  #branch: master

publish_mode: editorial_workflow  
media_folder: static/marketing/img
public_folder: /marketing/img

collections:
  - name: 'VJLP1-NoForm'
    label: 'Vera&John Template 1'
    format: 'frontmatter'
    folder: 'assets/content/landing-page/marketing/vjlp1'
    create: true
    identifier_field: "promo_banner.promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: vjlp1/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Country Language"
        name: "promo_country_lang"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}    
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
              - {label: "Game Logo", name: promo_game_logo, widget: image, required: false}
      - label: "Promotion Steps"
        name: "promo_steps" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Step 1 Title", name: promo_step_1_title, widget: "string"}
          - {label: "Step 1 Description", name: promo_step_1_desc, widget: "string"}
          - {label: "Step 2 Title", name: promo_step_2_title, widget: "string"}
          - {label: "Step 2 Description", name: promo_step_2_desc, widget: "string"}
          - {label: "Step 3 Title", name: promo_step_3_title, widget: "string"}
          - {label: "Step 3 Description", name: promo_step_3_desc, widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}    
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP1-NoForm"}
  - name: "VJLP3-NoForm"
    label: "Vera&John Template 3"
    format: 'frontmatter'
    folder: "assets/content/landing-page/marketing/vjlp3"
    create: true
    identifier_field: "promo_banner.promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: vjlp3/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Country Language"
        name: "promo_country_lang"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}   
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}     
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}    
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
          - label: "Game Slider"
            name: "game_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Game Icon 1", name: game_icon_1, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_1, widget: string, required: false, default: ""}
              - {label: "Game Icon 2", name: game_icon_2, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_2, widget: string, required: false, default: ""}
              - {label: "Game Icon 3", name: game_icon_3, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_3, widget: string, required: false, default: ""}
              - {label: "Game Icon 4", name: game_icon_4, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_4, widget: string, required: false, default: ""}
              - {label: "Game Icon 5", name: game_icon_5, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_5, widget: string, required: false, default: ""}
              - {label: "Game Icon 6", name: game_icon_6, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_6, widget: string, required: false, default: ""}
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP3-NoForm"}
      - {label: 'Body', name: 'body', widget: 'markdown' }